CREATE DATABASE serious_backend
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
 
USE serious_backend;

CREATE TABLE cuenta(
dni VARCHAR(9) NOT NULL UNIQUE KEY,
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255)  NOT NULL UNIQUE KEY,
contrasena VARCHAR(255) NOT NULL,
nombre VARCHAR(50) NULL,
apellido1 VARCHAR(100) NULL,
apellido2 VARCHAR(100) NULL,
peso DECIMAL(10,2) UNSIGNED NULL,
altura SMALLINT UNSIGNED NULL,
telefono VARCHAR(15) NULL,
fecha_nacimiento DATE NULL,
agua_deseada DECIMAL DEFAULT 2.5,
last_login DATETIME DEFAULT NULL);

CREATE TABLE bolso(
id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
color VARCHAR(40) NOT NULL,
primera_conexion DATE DEFAULT NULL,
cuenta BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (cuenta) REFERENCES cuenta(id)ON UPDATE CASCADE ON DELETE RESTRICT);
  
CREATE TABLE sensores(
id int AUTO_INCREMENT NOT NULL PRIMARY KEY,
tipo varchar(255) NOT NULL,
estado boolean NOT NULL
);

CREATE TABLE bolso_sensores(
bolso BIGINT NOT NULL,
sensor int NOT NULL,
FOREIGN KEY (bolso) REFERENCES bolso(id) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY (sensor) REFERENCES sensores(id) ON UPDATE CASCADE ON DELETE RESTRICT,
PRIMARY KEY (bolso, sensor));

CREATE TABLE medidas(
id varchar(255) NOT NULL PRIMARY KEY,
valor DECIMAL(10,2) NOT NULL);

CREATE TABLE sensores_medidas(
medida varchar(255) NOT NULL,
sensor int NOT NULL,
fecha_medida DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (sensor) REFERENCES sensores(id) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY (medida) REFERENCES medidas(id) ON UPDATE CASCADE ON DELETE RESTRICT,
PRIMARY KEY (sensor, medida,fecha_medida));