CREATE DATABASE opi_backend
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
 
USE opi_backend;

CREATE TABLE account(
    dni VARCHAR(9) NOT NULL UNIQUE KEY,
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE KEY,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NULL,
    last_name1 VARCHAR(100) NULL,
    last_name2 VARCHAR(100) NULL,
    weight DECIMAL(10,2) UNSIGNED NULL,
    height SMALLINT UNSIGNED NULL,
    phone VARCHAR(15) NULL,
    birth_date DATE NULL,
    desired_water DECIMAL DEFAULT 2.5,
    last_login DATETIME DEFAULT NULL
);

CREATE TABLE bag(
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    color VARCHAR(40) NOT NULL,
    first_connection DATE DEFAULT NULL,
    account BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (account) REFERENCES account(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE sensors(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL
);

CREATE TABLE bag_sensors(
    bag BIGINT NOT NULL,
    sensor INT NOT NULL,
    FOREIGN KEY (bag) REFERENCES bag(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (sensor) REFERENCES sensors(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (bag, sensor)
);

CREATE TABLE measurements(
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    value DECIMAL(10,2) NOT NULL
);

CREATE TABLE sensor_measurements(
    measurement VARCHAR(255) NOT NULL,
    sensor INT NOT NULL,
    measurement_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sensor) REFERENCES sensors(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (measurement) REFERENCES measurements(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (sensor, measurement, measurement_date)
);
